// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iovhbvruvpxwmskrnuuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvdmhidnJ1dnB4d21za3JudXVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTU5MTcsImV4cCI6MjA3MjMzMTkxN30.oifDSjWjkzineniKVBHy6Ypvp9bneeiTiZigf2B5hEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});